routes/dashboard.php
<?php

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');

//user crud   /* under testing*/
Route::resource('users', 'UserController');

Route::resource('settings', 'SettingController', ['except' => 'create']);

//products and sales
Route::resource('products', 'ProductController');
//Route::get('products/sale/{product}', 'SaleController@create')->name('products.saleForm');
Route::get('sales', 'SaleController@index')->name('sales.index');
Route::post('sales', 'SaleController@store')->name('sales.store');
Route::get('sales/{sale}', 'SaleController@show')->name('sales.show');
Route::delete('sales/{sale}', 'SaleController@destroy')->name('sales.destroy');
Route::get('sales/products/{product}', 'SaleController@create')->name('products.saleForm');
Route::get('sales/{sale}/products/{product}/edit', 'SaleController@edit')->name('sales.edit');
Route::put('sales/{sale}/products/{product}/edit', 'SaleController@update')->name('sales.update');

//installments
Route::get('installments', 'InstallmentController@index')->name('installments.index');
Route::get('installments/products/{product}', 'InstallmentController@create')->name('products.installmentForm');
Route::post('installments/products', 'InstallmentController@store')->name('installments.store');
Route::post('installments/products/group/{product}', 'InstallmentController@storeGroup')->name('installments.storeGroup');
Route::get('installments/{installment}', 'InstallmentController@show')->name('installments.show');
Route::get('installments/{installment}/products/{product}/edit', 'InstallmentController@edit')->name('installments.edit');
Route::put('installments/{installment}/products/{product}/update', 'InstallmentController@update')->name('installments.update');
Route::delete('installments/{installment}', 'InstallmentController@destroy')->name('installments.destroy');
Route::post('installmentsCount', 'CalculateController@installments')->name('installments.count');
Route::post('installmentsCollectedCount', 'CalculateController@collectedInstallments')->name('installments.collected.count');
Route::get('notifications', 'InstallmentController@notifications')->name('installments.notifications');

Route::resource('installmentGroups', 'InstallmentGroupController');
Route::get('installmentGroups/products/{product}', 'InstallmentController@group')->name('installment_groups.create');

//stores traders clients
Route::resource('stores', 'StoreController');
Route::resource('traders', 'TraderController');
Route::get('traders/{trader}/payments', 'TraderController@payments')->name('traders.payments');
Route::resource('clients', 'ClientController');

//calculations
Route::get('calculations', 'CalculateController@index')->name('calculations.index');
Route::post('calculations', 'CalculateController@counts')->name('calculations.counts');

Route::post('insert', 'SettingController@put')->name('insert');



Route::get('search', 'HomeController@search')->name('search');
Route::get('search/{store}', 'StoreController@search')->name('store.search');

Route::resource('collecteds','CollectedController');
Route::get('collecteds/installments/{installment}/index','CollectedController@index')->name('collecteds.index');
Route::get('collecteds/installments/{installment}','CollectedController@create')->name('collecteds.create');
Route::get('collecteds/{collected}/installments/{installment}','CollectedController@edit')->name('collecteds.edit');
Route::put('collecteds/{collected}/installments/{installment}','CollectedController@update')->name('collecteds.update');

Route::resource('bills', 'BillController');
Route::get('bills/{bill}/pdf', 'BillController@pdf')->name('bills.pdf');
Route::get('excel', 'BillController@excelReport')->name('bills.excel');

Route::resource('payments', 'PaymentController');
Route::resource('expenses', 'ExpenseController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/home', function () {
    return redirect('/dashboard');
});

resources/views/dashboard/layouts/sidebar/main.blade.php
<div class="sidebar sidebar-main">
    <div class="sidebar-content">

        <!-- Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
                <ul class="navigation navigation-main navigation-accordion">

                    <li class="{{ css_route_active('dashboard.home') }}">
                        <a href="{{ dashboard_route('home') }}">
                            <i class="icon-home4"></i>
                            <span>@lang('dashboard.sidebar.links.home')</span>
                        </a>
                    </li>

                    <!-- Sales navigation -->

                    <li class="{{ css_resource_active('dashboard.sales') }}">
                        <a href="{{ dashboard_route('sales.index') }}">
                            <i class="icon-cart5" style="color: yellowgreen"></i>
                            <span>@lang('sales.plural')</span>
                        </a>
                    </li>


                    <!---- Admin navigation ----->

                @if(auth()->user()->isAdmin() || auth()->user()->isPoss())

                    <!-- Sproducts navigation -->

                        <li class="{{ css_resource_active('dashboard.products') }}">
                            <a href="{{ route('dashboard.products.index') }}">
                                <i class="icon-grid4"></i>
                                <span>@lang('products.plural')</span>
                            </a>
                        </li>

                        <!-- Stores navigation -->

                        <li class="{{ css_resource_active('dashboard.stores') }}">
                            <a href="{{ dashboard_route('stores.index') }}">
                                <i class=" icon-location4" style="color: yellowgreen"></i>
                                <span>@lang('stores.plural')</span>
                            </a>
                        </li>
                        <!-- Traders navigation -->

                        <li class="{{ css_resource_active('dashboard.traders') }}">
                            <a href="{{ dashboard_route('traders.index') }}">
                                <i class="icon-person"></i>
                                <span>@lang('traders.plural')</span>
                            </a>
                        </li>
                        <!-- Clients navigation -->

                        <li class="{{ css_resource_active('dashboard.clients') }}">
                            <a href="{{ dashboard_route('clients.index') }}">
                                <i class="icon-person" style="color: yellowgreen"></i>
                                <span>@lang('clients.plural')</span>
                            </a>
                        </li>
                        <!-- Installments navigation -->

                        <li class="{{ css_resource_active('dashboard.installments') }}">
                            <a href="{{ dashboard_route('installments.index') }}">
                                <i class="icon-cabinet"></i>
                                <span>@lang('installments.plural')</span>
                            </a>
                        </li>
                        <!-- Installments group -->

                        <li class="{{ css_resource_active('dashboard.installmentGroups') }}">
                            <a href="{{ dashboard_route('installmentGroups.index') }}">
                                <i class="icon-cabinet" style="color: yellowgreen"></i>
                                <span>@lang('installmentGroups.plural')</span>
                            </a>
                        </li>

                        <!-- Users navigation -->

                        <li class="{{ css_resource_active('dashboard.users') }}">
                            <a href="{{ dashboard_route('users.index') }}">
                                <i class="icon-users"></i>
                                <span>@lang('users.plural')</span>
                            </a>
                        </li>
                        <!-- Calculations navigation -->


                        <li class="treeview {{ css_resource_active('dashboard.calculations') }}">
                            <a href="{{ route('dashboard.calculations.index') }}">
                                <i class="icon-stats-growth" style="color: yellowgreen"></i> <span>{{  trans('calculations.plural') }}</span>
                                <span class="pull-right-container">
                                   <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                        </li>
                        <!-- Bills navigation -->


                        <li class="treeview {{ css_resource_active('dashboard.bills') }}">
                            <a href="{{ route('dashboard.bills.index') }}">
                                <i class="icon-copy"></i> <span>{{  trans('bills.plural') }}</span>
                                <span class="pull-right-container">
                                   <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                        </li>
                        <!-- Payments navigation -->


                        <li class="treeview {{ css_resource_active('dashboard.payments') }}">
                            <a href="{{ route('dashboard.payments.index') }}">
                                <i class=" icon-coin-pound" style="color: yellowgreen"></i> <span>{{  trans('payments.plural') }}</span>
                                <span class="pull-right-container">
                                   <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                        </li>
                        <!-- Expenses navigation -->


                        <li class="treeview {{ css_resource_active('dashboard.expenses') }}">
                            <a href="{{ route('dashboard.expenses.index') }}">
                                <i class=" icon-cash"></i> <span>{{  trans('expenses.plural') }}</span>
                                <span class="pull-right-container">
                                   <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                        </li>
                        <!-- Settings navigation -->

                        <li class="{{ css_resource_active('dashboard.settings') }}">
                            <a href="{{ route('dashboard.settings.index') }}">
                                <i class="icon-cog"></i>
                                <span>@lang('settings.plural')</span>
                            </a>
                        </li>

                @endif

                <!-- /main -->
                </ul>
            </div>

        </div>
        <!-- /main navigation -->
        {{-- @include('dashboard.sidebar.items') --}}
    </div>
</div>