routes/dashboard.php
<?php

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');

//user crud   /* under testing*/
Route::resource('users', 'UserController');

Route::resource('settings', 'SettingController', ['except' => 'create']);

//products and sales
Route::resource('products', 'ProductController');
//Route::get('products/sale/{product}', 'SaleController@create')->name('products.saleForm');
Route::get('sales', 'SaleController@index')->name('sales.index');
Route::post('sales', 'SaleController@store')->name('sales.store');
Route::get('sales/{sale}', 'SaleController@show')->name('sales.show');
Route::delete('sales/{sale}', 'SaleController@destroy')->name('sales.destroy');
Route::get('sales/products/{product}', 'SaleController@create')->name('products.saleForm');
Route::get('sales/{sale}/products/{product}/edit', 'SaleController@edit')->name('sales.edit');
Route::put('sales/{sale}/products/{product}/edit', 'SaleController@update')->name('sales.update');

//installments
Route::get('installments', 'InstallmentController@index')->name('installments.index');
Route::get('installments/products/{product}', 'InstallmentController@create')->name('products.installmentForm');
Route::post('installments/products', 'InstallmentController@store')->name('installments.store');
Route::post('installments/products/group/{product}', 'InstallmentController@storeGroup')->name('installments.storeGroup');
Route::get('installments/{installment}', 'InstallmentController@show')->name('installments.show');
Route::get('installments/{installment}/products/{product}/edit', 'InstallmentController@edit')->name('installments.edit');
Route::put('installments/{installment}/products/{product}/update', 'InstallmentController@update')->name('installments.update');
Route::delete('installments/{installment}', 'InstallmentController@destroy')->name('installments.destroy');
Route::post('installmentsCount', 'CalculateController@installments')->name('installments.count');
Route::post('installmentsCollectedCount', 'CalculateController@collectedInstallments')->name('installments.collected.count');
Route::get('notifications', 'InstallmentController@notifications')->name('installments.notifications');

Route::resource('installmentGroups', 'InstallmentGroupController');
Route::get('installmentGroups/products/{product}', 'InstallmentController@group')->name('installment_groups.create');

//stores traders clients
Route::resource('stores', 'StoreController');
Route::resource('traders', 'TraderController');
Route::get('traders/{trader}/payments', 'TraderController@payments')->name('traders.payments');
Route::resource('clients', 'ClientController');

//calculations
Route::get('calculations', 'CalculateController@index')->name('calculations.index');
Route::post('calculations', 'CalculateController@counts')->name('calculations.counts');

Route::post('insert', 'SettingController@put')->name('insert');



Route::get('search', 'HomeController@search')->name('search');
Route::get('search/{store}', 'StoreController@search')->name('store.search');

Route::resource('collecteds','CollectedController');
Route::get('collecteds/installments/{installment}/index','CollectedController@index')->name('collecteds.index');
Route::get('collecteds/installments/{installment}','CollectedController@create')->name('collecteds.create');
Route::get('collecteds/{collected}/installments/{installment}','CollectedController@edit')->name('collecteds.edit');
Route::put('collecteds/{collected}/installments/{installment}','CollectedController@update')->name('collecteds.update');

Route::resource('bills', 'BillController');
Route::get('bills/{bill}/pdf', 'BillController@pdf')->name('bills.pdf');
Route::get('excel', 'BillController@excelReport')->name('bills.excel');

Route::resource('payments', 'PaymentController');
Route::resource('expenses', 'ExpenseController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/home', function () {
    return redirect('/dashboard');
});

app/Http/Controllers/Dashboard/BillController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Bill;
use PDF;
use Excel;
use Illuminate\Http\Request;
use App\Services\BillService;

class BillController extends Controller
{

    public $bill;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bills = Bill::latest()->paginate(15);

        return view('dashboard.bills.index', compact('bills'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bill = new Bill;
        return view('dashboard.bills.create', compact('bill'));
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request)
    {
        Bill::create($request->all());

        return $this->redirectToIndexWithFlash('created');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bill $bill
     * @return \Illuminate\Http\Response
     */
    public function show(Bill $bill)
    {
        if ($bill->type == 1) {
            $installments = $bill->installments;
        } elseif ($bill->type == 2) {
            $installments = $bill->sales;
        }
        //$installments = $bill->installments ? $bill->installments : $bill->sales;

        return view('dashboard.bills.show', compact('bill', 'installments'));

    }

    /**
     * @param Bill $bill
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Bill $bill)
    {
        if ($bill->type = 1) {
            $installments = $bill->installments;
        }
        if ($bill->type = 2) {
            $installments = $bill->sales;
        }

        return view('dashboard.bills.edit', compact('bill', 'installments'));

    }

    /*
     *
     */
    public function update(Request $request, Bill $bill)
    {
        $bill->update($request->all());

        return $this->redirectToIndexWithFlash('updated');

    }

    public function destroy(Bill $bill)
    {
        $bill->delete();
        return $this->redirectToIndexWithFlash('deleted');

    }


    /**
     * @return pdf show and download
     */
    public function pdf(Bill $bill)
    {
        if ($bill->type == 1) {
            $installments = $bill->installments;
        } else{
            $installments = $bill->sales;
        }

        //
        //$installments = $bill->installments ? $bill->installments : $bill->sales;
        if ($bill->type ==1) {
            $all = $bill->installments->sum('all');
        }elseif($bill->type == 2) {
            $all = $bill->sales->sum('all');
        }
        $pdf = PDF::loadView('dashboard.bills.pdf', compact('all', 'installments', 'sales', 'bill'));
        //return $pdf->download('dashboard.bills.pdf');
        return $pdf->stream('dashboard.bills.pdf');
    }


}

app/Http/Controllers/Dashboard/CalculateController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Expense;
use App\Models\Installment;
use App\Models\Sale;
use Illuminate\Http\Request;

class CalculateController extends Controller
{
    public $sales;
    public $installments;
    public $collectedInstallments;

    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->middleware('admin');

    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
          return view('dashboard.calculations.index');
    }



    public function counts(Request $request)
    {
        $from = $request->from;
        $to = $request->to;
        $sales = Sale::whereDate('created_at', '>=', $from)->whereDate('created_at', '<=', $to)->sum('all');
        $installments = Installment::whereDate('created_at', '>=', $from)->whereDate('created_at', '<=', $to)->sum('all');
        $collectedInstallments = Installment::whereDate('created_at', '>=', $from)->whereDate('created_at', '<=', $to)->sum('collected');
        $expenses = Expense::whereDate('created_at', '>=', $from)->whereDate('created_at', '<=', $to)->sum('amount');

        return view('dashboard.calculations.show', compact('expenses','collectedInstallments','installments','sales'));

    }
//
//    public function installments(Request $request)
//    {
//        $from = $request->from;
//        $to = $request->to;
//        $installments = Installment::where('created_at', '>=', $from)->where('created_at', '<=', $to)->sum('all');
//        $this->installments = $installments;
//
//    }
//
//    public function collectedInstallments(Request $request)
//    {
//        $from = $request->from;
//        $to = $request->to;
//        $collectedInstallments = Installment::where('created_at', '>=', $from)->where('created_at', '<=', $to)->sum('collected');
//        $this->collectedInstallments = $collectedInstallments;
//
//    }
}

app/Http/Controllers/Dashboard/ClientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Client;
use App\Models\Installment;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * ClientController constructor.
     */
    public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->paginate(15);

        return view('dashboard.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::all()->pluck('name', 'id');
        return view('dashboard.clients.create', compact('clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */


    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        $installments = $client->installments()->paginate();
        $all = $installments->sum('collected');
        $remainning = $installments->sum('all') - $all;
        return view('dashboard.clients.show', compact('all', 'installments', 'client','remainning'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('dashboard.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Client $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $client->update($request->all());
        $this->flash('updated')->success();
        return redirect()->route('dashboard.clients.show', $client);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        //
    }
}

app/Http/Controllers/Dashboard/CollectedController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Collected;
use App\Models\Installment;
use Illuminate\Http\Request;

class CollectedController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Installment $installment)
    {
        $collecteds = $installment->collecteds;

         return view('dashboard.collecteds.index', compact('collecteds','installment'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Installment $installment)
    {
        $collected = new Collected ;
        return view('dashboard.collecteds.create', compact( 'collected','installment'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Installment $installment)
    {
        $collected = new Collected ;
        $collected->date = $request->date;
        $collected->installment_id = $request->installment_id;
        $collected->collected = $request->collected;

        $collected->save();

        $collected->installment->increment('collected', $request->collected);

        flash(trans('collecteds.flash.created'))->success();

        return redirect()->route( 'dashboard.collecteds.index', $collected->installment);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ollected  $collected
     * @return \Illuminate\Http\Response
     */
    public function show(Collected $collected)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Collected  $collected
     * @return \Illuminate\Http\Response
     */
    public function edit(Collected $collected, Installment $installment)
    {
         return view('dashboard.collecteds.edit', compact( 'collected','installment'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Collected  $collected
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Collected $collected)
    {
        $collected->installment->decrement('collected', $collected->collected);

        $collected->date = $request->date;
        $collected->installment_id = $request->installment_id;
        $collected->collected = $request->collected;

        $collected->update();

        $collected->installment->increment('collected', $request->collected);

        flash(trans('collecteds.flash.updated'))->success();

        return redirect()->route( 'dashboard.collecteds.index', $collected->installment);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Collected  $collected
     * @return \Illuminate\Http\Response
     */
    public function destroy(Collected $collected)
    {
        $collected->installment->decrement('collected', $collected->collected);

        $collected->delete();

        flash(trans('collecteds.flash.deleted'))->success();

        return redirect()->route( 'dashboard.collecteds.index', $collected->installment);
    }
}

app/Http/Controllers/Dashboard/Controller.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller as BaseController;

class Controller extends BaseController
{
    /**
     * The default page size for eloquent.
     *
     * @var int
     */
    protected $pageSize = 15;

    /**
     * Send a flash message and Redirect to index.
     *
     * @param  string $event
     * @param  string $level
     * @param  string $resource
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function redirectToIndexWithFlash($event = 'created', $level = 'success', $resource = null)
    {
        $this->flash($event, $level, $resource);


        return $this->redirectToIndex($resource);
    }

    /**
     * Send a flash message.
     *
     * @param  string $event
     * @param  string $level
     * @param  string $resource
     *
     * @return \Laracasts\Flash\FlashNotifier
     */
    public function flash($event = 'created', $level = 'success', $resource = null)
    {
        if (! $resource) {
            $resource = $this->guessResourceName();
        }

        return flash(trans($resource . '.messages.' . $event), $level);
    }

    /**
     * Redirect to index.
     *
     * @param null $resource
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function redirectToIndex($resource = null)
    {
        if (! $resource) {
            $resource = $this->guessResourceName();
        }

        return redirect()->route("dashboard.$resource.index");
    }

    public function redirectToBack($resource = null)
    {
        if (! $resource) {
            $resource = $this->guessResourceName();
        }

        return redirect()->route("create");
    }

    /**
     * Guess the resource name of the controller.
     *
     * @return string
     */
    protected function guessResourceName()
    {
        $classBaseName = class_basename(get_class($this));

        return str_plural(snake_case(str_replace('Controller', '', $classBaseName)));
    }
}

resources/views/dashboard/clients/create.blade.php
@php($title = trans('clients.actions.add'))

@extends('dashboard.layouts.main', ['title' => $title])

@section('content')

    @component('dashboard.components.page', ['header_title' => $title])

        @slot('breadcrumb')
            <li>
                <a href="{{ dashboard_route('clients.index') }}">
                    @lang('clients.plural')
                </a>
            </li>

            <li class="active">
                {{ $title }}
            </li>
        @endslot

        @component('dashboard.components.panel', [
            'heading' => trans('clients.info'),
            'mode' => 'primary',
        ])

            {{ Form::open(['route' => ['dashboard.clients.store'], 'class' => 'form-horizontal', 'files' => true]) }}

            @include('dashboard.clients.partials.form', ['submitLabel' => trans('forms.add')])

            {{ Form::close() }}

        @endcomponent

    @endcomponent

@endsection

resources/views/dashboard/clients/edit.blade.php
@php($title = trans('clients.singular') . ' : ' . $client->name)

@extends('dashboard.layouts.main', ['title' => $title])

@section('content')

    @component('dashboard.components.page', ['header_title' => $title])

        @slot('breadcrumb')
            <li>
                <a href="{{ dashboard_route('clients.index') }}">
                    @lang('clients.plural')
                </a>
            </li>

            <li>
                {{ $title }}
            </li>
        @endslot

        @component('dashboard.components.panel', [
            'heading' => $title,
            'mode' => 'primary',
        ])

            {{ Form::model( $client, ['route' => ['dashboard.clients.update', $client], 'method' => 'patch', 'class' => 'form-horizontal', 'files' => true]) }}

            @include('dashboard.clients.partials.form', ['submitLabel' => trans('forms.edit')])

            {{ Form::close() }}

        @endcomponent

    @endcomponent

@endsection

resources/views/dashboard/clients/index.blade.php
@php($title = trans('clients.plural'))

@extends('dashboard.layouts.main', ['title' => $title])

@section('content')

    @component('dashboard.components.page', ['header_title' => $title])

        @slot('breadcrumb')
            <li class="active">
                {{ $title }}
            </li>
        @endslot

        @can('create', \App\Models\Client::class)
            @slot('header_elements')
                <a href="{{ dashboard_route('clients.create') }}" class="btn btn-primary">
                    @lang('clients.actions.add')
                    <i class="icon-plus3"></i>
                </a>
            @endslot
        @endcan
        @component('dashboard.components.list', ['model' => $clients])
            @slot('thead')
                <th style="font-size: 16px;font-weight: bold;">@lang('clients.attributes.name')</th>
                <th style="font-size: 16px;font-weight: bold;">@lang('clients.attributes.phone')</th>
                <th style="font-size: 16px;font-weight: bold;">...</th>
            @endslot


            @slot('tbody')

                @foreach ($clients as $client)

                    <tr>
                        <td>
                            <a href="{{ dashboard_route('clients.show', $client) }}"  style="font-size: 19px; color: #26a69a;">
                                {{ $client->name }}
                            </a>
                        </td>
                        <td>
                            {{ $client->phone }}

                        </td>

                        <td class=" table-actions">
                            @can('update', $client)
                                <a
                                        href="{{ dashboard_route('clients.edit', $client) }}"
                                        class="btn btn-default text-info btn-xs"
                                >
                                    @lang('forms.edit')
                                    <i class="icon-pencil7"></i>
                                </a>
                            @endcan
                            @can('delete', $client)
                                <a
                                        href="javascript:void(0)"
                                        class="delete-confirm btn btn-default text-danger btn-xs"
                                        data-url="{{ dashboard_route('clients.destroy', $client) }}"
                                        data-title="@lang('clients.dialogs.delete.title', ['item' => $client->name])"
                                        data-message="@lang('clients.dialogs.delete.info')"
                                >
                                    @lang('forms.delete')
                                    <i class="icon-trash"></i>
                                </a>
                            @endcan
                        </td>
                    </tr>
                @endforeach

            @endslot

        @endcomponent

    @endcomponent

@endsection

resources/views/dashboard/clients/show.blade.php
@php($title = trans('clients.singular') . ' : ' . $client->name)

@extends('dashboard.layouts.main', ['title' => $title])

@section('content')

    @component('dashboard.components.page', ['header_title' => $title])

        @slot('breadcrumb')
            <li>
                <a href="{{ dashboard_route('clients.index') }}">
                    @lang('clients.plural')
                </a>
            </li>

            <li>
                {{ $title }}
            </li>

            <span class="text-success" style="padding: 20px;font-size: 20px;">
                @lang('clients.collected') : {{ $all }}
            </span>
            <span class="text-danger" style="padding: 20px;font-size: 20px;">
                @lang('clients.remainning') : {{ $remainning }}
            </span>
            {{--<span class="text-primary" style="padding: 20px;font-size: 20px;">--}}
                {{--@lang('products.attributes.wholesales') : {{ $wholesales }}--}}
            {{--</span>--}}
        @endslot

        @component('dashboard.components.list', ['model' => $installments])
            @slot('thead')
                <th style="font-size: 16px;font-weight: bold;">@lang('installments.attributes.name')</th>
                <th style="font-size: 16px;font-weight: bold;">@lang('installments.attributes.saler')</th>
                <th style="font-size: 16px;font-weight: bold;">@lang('installments.attributes.installment_count')</th>
                <th style="font-size: 16px;font-weight: bold;">@lang('installments.attributes.installment')</th>
                <th style="font-size: 16px;font-weight: bold;">@lang('installments.attributes.collected')</th>
                <th style="font-size: 16px;font-weight: bold;"> باقى </th>
                <th style="font-size: 16px;font-weight: bold;">@lang('sales.attributes.date')</th>
                <th style="font-size: 16px;font-weight: bold;">...</th>
            @endslot


            @slot('tbody')

                @foreach ($installments as $installment)

                    <tr>
                        <td>
                            <a href="{{ dashboard_route('installments.show', $installment) }}"
                               style="font-size: 19px; color: #26a69a"
                               class="text-primary ">
                                {{ $installment->product['name'] }}
                            </a>
                        </td>

                        <td>

                            {{ $installment->user->name }}

                        </td>

                        <td>
                            {{ $installment->count }}
                        </td>

                        <td>
                            {{ $installment->cost }}
                        </td>
                        <td>
                            @php($sum = $installment->collecteds->sum('collected'))
                            @if($sum >0)
                                {{ $sum }}
                                <a href="{{ dashboard_route('collecteds.index', $installment) }}">
                                    <button class="btn btn-info">{{ trans('collecteds.info') }}</button>
                                </a>
                            @else
                                <span class="text-danger"> {{ trans('collecteds.empty') }}</span>
                            @endif

                        </td>
                        @php($rem = $installment->all - $sum)
                        <td class=" @if($rem > 0) text-danger @else text-success @endif">
                            {{ $rem }}
                        </td>

                        <td>
                            {{ $installment->created_at->format('Y-m-d H:i') }}
                        </td>

                        <td>
                            @php($product = $installment->product)
                            @can('update', $installment)
                                <a href="{{ dashboard_route('collecteds.create', $installment) }}"
                                   class="btn btn-primary">
                                    @lang('collecteds.actions.add')
                                    <i class="icon-plus3"></i>
                                </a>
                                <a
                                        href="{{ dashboard_route('installments.edit',[ $installment, $product]) }}"
                                        class="btn btn-default text-info btn-xs"
                                >
                                    @lang('forms.edit')
                                    <i class="icon-pencil7"></i>
                                </a>
                            @endcan
                            @can('delete', $installment)
                                <a
                                        href="javascript:void(0)"
                                        class="delete-confirm btn btn-default text-danger btn-xs"
                                        data-url="{{ dashboard_route('installments.destroy', $installment) }}"
                                        data-title="@lang('installments.dialogs.delete.title', ['item' => $installment->product['name']])"
                                        data-message="@lang('installments.dialogs.delete.info')"
                                >
                                    @lang('forms.delete')
                                    <i class="icon-trash"></i>
                                </a>
                            @endcan
                        </td>
                    </tr>
                @endforeach

            @endslot

        @endcomponent

    @endcomponent

@endsection